### ISSUE TITLE
L2/R2 Not Bound To Controller

### ISSUE THREAD

**Issue by Jgr9** [TheOfficialFloW/MiniVitaTV#1]
Unless I'm missing something, L2 and R2 are not bound to the controller when using this.

**Comment by ticaso** [comment]
u right

**Comment by TheOfficialFloW** [comment]
Check if v0.2 fixes that

**Comment by Jgr9** [comment]
Black screen after the Enso logo with the card in.  I think you've bricked my card.

**Comment by TheOfficialFloW** [comment]
Sorry you stupid?

**Comment by Jgr9** [comment]
How do you suggest I remove them from the cfg now if I can't boot fully with the card in?

**Comment by TheOfficialFloW** [comment]
My nerves...Hold L while booting to skip plugins

**Comment by Jgr9** [comment]
Ok, thank you very much.  I wasn't aware that was a feature.  If it's somehow related, here's my config.  I'm well aware that it's a redundant mess from when I was trying to figure out how it worked or should be formatted.

`# You must reboot for changes to take place.
*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ux0:plugins/vitabright.skprx
ux0:tai/minivitatv.skprx
ux0:tai/ds3.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ux0:app/MLCL00001/henkaku.suprx
ux0:tai/download_enabler.suprx
ux0:tai/minivitatv.suprx
*NPXS10015
# this is for modifying the version string
ux0:app/MLCL00001/henkaku.suprx
*PCSE00070
# *ALL
ux0:plugins/netcheck_bypass.suprx
vs0:sys/external/libpgf.suprx
*NPEZ00104
ux0:adrenaline/adrenaline.suprx

*NPXS10016
# this is for modifying the version string in settings widget
ux0:app/MLCL00001/henkaku.suprx

# henkaku.suprx and henkaku.skprx has moved to ur0:tai, you may remove
# the old entries above.
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx`

**Comment by ccfman2004** [comment]
Will L2/R2 ever be redirected from the rear touch screen to the controller as it's impossible to play some games that use the rear touch screen to simulate the L2/R2 buttons?

**Comment by TheOfficialFloW** [comment]
See if this solves the problem: https://drive.google.com/file/d/1aLQsQAFG4lBKJMpVgn2kJxHQfvOKeYwN/view?usp=sharing

**Comment by Jgr9** [comment]
Is that the same one as before?

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/MiniVitaTV/releases/tag/v0.2

**Comment by Jgr9** [comment]
Because I didn't know if you were shoving me off and just having someone else test the same file.

**Comment by Jgr9** [comment]
Ok, so the suprx isn't required anymore?  Because it still shut down on boot when I tried to use it.  I disabled that and it seems to be working as it should with both of the skprx enabled, though I only used a DS4.

**Comment by Jgr9** [comment]
Do you have a working version of the SixaxisPairTool for DS3 (for Windows 10)?  The download doesn't seem to work properly and I'm having Visual Studio version issues with the old one.
