### ISSUE TITLE
Locked out of Vita because of the plugin, what to do?

### ISSUE THREAD

**Issue by GamerzHell9137** [TheOfficialFloW/MiniVitaTV#14]

**Comment by TheOfficialFloW** [comment]
learn how to read. "If you're using enso you should boot with L trigger hold to skip plugins in case you want to remove this plugin. Remember it's a beta."

**Comment by GamerzHell9137** [comment]
I'm not using Enso.

**Comment by TheOfficialFloW** [comment]
just hold L when booting henkaku/h-encore then.

**Comment by GamerzHell9137** [comment]
@TheOfficialFloW Thanks, one of the discord people said that too, works fine now. Anyways, is the DS4 v2 the reason why it doesn't want to connect? I know v2 had some issues connecting on PC when it released.
