### ISSUE TITLE
Dualshock AND Vita Controllers Support 

### ISSUE THREAD

**Issue by robertSandro** [TheOfficialFloW/MiniVitaTV#16]
I think I'm not the one who wants this function. The Plug-in is already awesome, but carry two gamepads is pretty bad. So I wondering if it's possible to do this. Thanks TheFlow... You're awesome!!!

**Comment by nanashi89** [comment]
It's currently in the beta stage, IIRC.
But, yeah, this needs to be upgraded.

**Comment by TheOfficialFloW** [comment]
Fixed with beta 4. https://github.com/TheOfficialFloW/MiniVitaTV/pull/26
