### ISSUE TITLE
Volume buttons don't work

### ISSUE THREAD

**Issue by afdc98** [TheOfficialFloW/MiniVitaTV#18]
Hello. When using this plugin, upper volume buttons on the PSVita stop working, so there's no way to modify the volume of the system. Thank you.

**Comment by TheOfficialFloW** [comment]
Read the readme.

**Comment by afdc98** [comment]
Don't treat me like I'm stupid. I read the readme. I'm just pointing out this is a problem, since there is no other way no modify the volume. Whatever.

You really need to chill sometimes.

**Comment by TheOfficialFloW** [comment]
The readme says that physical buttons don‘t work yet, so you‘re just reporting a known issue. Also not sure who has to calm down.
