### ISSUE TITLE
I have a few errors...

### ISSUE THREAD

**Issue by vitajr** [TheOfficialFloW/MiniVitaTV#2]
So, just today I installed the plugin on my vita slim, had some trouble connecting my PS4 controller until finally it started working. I guess I'm the one at fault when it came to connecting the controller. However regarding the controller problem, I tried starting up a few games from my physical and digital collection on the system and the same error occurred stating the following code: (C2-15411-2) This same error appeared when I was trying to boot up Adrenaline.
Another error appeared when I tried to refresh the live area of all my applications/games the error code is as follows: (C0-11274-5).
Finally, there are some games that are not supported.. These games from my collection are Terraria and Vitamin Z
Hope you can fix the issues. Keep up the hard work!

**Comment by TheOfficialFloW** [comment]
Not related to minivitatv

**Comment by vitajr** [comment]
How is it not related to minivitatv if the all the errors minus the controller thing never appeared when I deleted the plugin?

**Comment by TheOfficialFloW** [comment]
It is a beta. I removed beta 2 now.
