### ISSUE TITLE
do not activate ds3.skprx only

### ISSUE THREAD

**Issue by Zeitwaechter** [TheOfficialFloW/MiniVitaTV#3]
I thought of using ds3.skprx only to enable DS4 Support while using the shipped version of this Repository.

While first enabling all three (beta 2) of them to test it out I reduced the enabled Plugins to ds3.skprx only and now I'm kinda stuck while having my DS4 Controller enabled and not being able to use the controlls of the PS Vita what means I can't use VitaShell to disable the last one.

Maybe this information might help others.

**Comment by Zeitwaechter** [comment]
Welp.
VitaShell still doesn't support any physical keyboard either.

#sadface

Looks like I have to redo the whole enso thing from the beginning..?

**Comment by TheOfficialFloW** [comment]
Just fucking boot enso with L trigger hold to skip plugins
