### ISSUE TITLE
Touchpad support

### ISSUE THREAD

**Issue by HRudyPlayZ** [TheOfficialFloW/MiniVitaTV#35]
Can you please add DS4's touchpad support so when you touch it, it acts as the front touchscreen? Like on DS4Vita?
This is the most lacking thing... You don't have to add any kind of reartouch support as we can use TouchRemap / RemapPSV for that, but please add the normal frontscreen :)

**Comment by NeoTechni** [comment]
Yes please, I got stuck in Disney Infinity because to exit a menu you need to touch the screen, and nothing works.

**Comment by MERLev** [comment]
You can try this for now https://github.com/MERLev/ds4Touch

**Comment by NayoMays** [comment]
Hey @HRudyPlayZ, I would close this issue. The plugin @MERLev linked can be installed with Auto Plugins II, and works perfectly. Thanks!
