### ISSUE TITLE
Freeze PSVita

### ISSUE THREAD

**Issue by chronoss09** [TheOfficialFloW/MiniVitaTV#4]
When both plugin are activated on the same psvita, all boutons doesn't work. Only the touch screen work...

Tested on 3.65 !

**Comment by masoudr** [comment]
@chronoss09 This is a known problem and @TheOfficialFloW already said that. I think it can be fixed easily 
 because old `ds4vita` didn't have this problem. If you get stuck you can press `L` on boot to disable the plugin and then remove it.
