### ISSUE TITLE
Release for v0.2

### ISSUE THREAD

**Issue by masoudr** [TheOfficialFloW/MiniVitaTV#5]
Hi,
I cant find a binary release for v0.2 or any change logs.Can you please provide it?
Will be any fix for disabled buttons, Is the cause of problem known yet?
Thanks.

**Comment by TerableSpelar** [comment]
If the vita thinks it’s a pstv, it makes sense for system buttons to be disabled (pstv doesn’t have buttons!). I find this feature extremely useful as I don’t have analog sticks on my vita and this allows me to use an external controller without X and Y axis set to “0”.

**Comment by TheOfficialFloW** [comment]
No.
