### ISSUE TITLE
Does this support L2 and R2 triggers?

### ISSUE THREAD

**Issue by nanashi89** [TheOfficialFloW/MiniVitaTV#6]
Wanna make the transition from DS4Vita to this, but has L2 R2 support been added?

**Comment by TheOfficialFloW** [comment]
Can you see if this adds support for L2/R2? https://drive.google.com/file/d/1aLQsQAFG4lBKJMpVgn2kJxHQfvOKeYwN/view?usp=sharing

**Comment by nanashi89** [comment]
Works great!
 
Thanks!

Holy crud! You even have rumble on this?? You really went all out! Thanks again!

**Comment by TheOfficialFloW** [comment]
Ok thanks for testing, offically released now: https://github.com/TheOfficialFloW/MiniVitaTV/releases/tag/v0.2

**Comment by ccfman2004** [comment]
I am using a DS4 controller and I get no response from using L2/R2 using beta 2.  Oddly enough the rear touchpad responds for L2/R2 emulation.  The game is Ratchet and Clank Collection where the L2/R2 is mapped to the rear touchpad.
