### ISSUE TITLE
Not issue but a question

### ISSUE THREAD

**Issue by FSEC-DALMASIAN** [TheOfficialFloW/MiniVitaTV#7]
@theofficialflow could you please add support for the actual Vita buttons and joisticks so I don't have to disable the plugin and re-enable it every time

I'm creating a tvdock that implementa the pocv5 and this plugin to make this 100% better than the switch haha

**Comment by BOBdotEXE** [comment]
> Known issues:
> Cannot use physical buttons **yet**
https://github.com/TheOfficialFloW/MiniVitaTV
 
It's still being worked on, for now if you need both, you can still use the old ds4 plugin.
 
But it would be cool if this plugin had a toggle key-combo,
so even if we can't use both at the same time, we could at least turn it off, when needed.

**Comment by FSEC-DALMASIAN** [comment]
if not enough buttons on the vita are an issue implement support for the trigger grips that use the rear touchpad for r2 l2 and r3 and l3, i have it and its the way to go even if your not gonna use em. i think that this addon to this plugin would be a peice of cake for @TheOfficialFloW he is a smart guy just saying. yeah you could have a button that enables and disables the plugin but that is basicaly the same as going into the config file and commenting it out so that is out of the picture.

Please @TheOfficialFloW implement this. everyone that uses this plugin would want this not just me. this would help out allot for the dock i am creating using 3d printed parts and a raspberry pi. 

Thank-u

**Comment by masoudr** [comment]
@FSEC-DALMASIAN I think the whole problem can be fixed in future so no need to implement this functionality. The only problem with old `ds4vita` is just optimizing for the new firmware like 3.65, 3.68 but it lacks for multiplayer.

**Comment by TheOfficialFloW** [comment]
„Please do this, please do that“ - am I your fucking personal programmer or what
