### ISSUE TITLE
PSX games don't respond!

### ISSUE THREAD

**Issue by HeczJoker** [TheOfficialFloW/MiniVitaTV#9]
So I found out that having this plugin would make PSX games non-responsive on Adrenaline, not Adrenaline itself. Had to disable it in order to run my PSX game normally. Will wait until an update fixes this issue. Also found out that using ds3 plugin completely makes any application un-responsive as well.

**Comment by TheOfficialFloW** [comment]
You realize physical buttons stop working with this plugin?
